### ISSUE TITLE
Change Client.reply/2 to Client.send/2

### ISSUE THREAD

**Issue by wende** [hedwig-im/hedwig#10]
I've been using Hedwig for my project lately, and I don't know how about the others but I find Client.reply/2 name pretty ambiguous, especially that it's something not related to Handler.reply/2. I guess adding new function that is called `send` instead of `reply` would be more readable and intuitive for newcomers.

**Comment by scrogson** [comment]
@iraasta yes, I agree. I need to revisit this very soon. Thanks for bringing it up :+1:

**Comment by iraasta** [comment]
Also I wanted to thank You because this library was extremely useful for me lately :)

**Comment by scrogson** [comment]
Excellent to hear :smile:
