### ISSUE TITLE
More verbous error on connection failure

### ISSUE THREAD

**Issue by wende** [hedwig-im/hedwig#11]
Right now when hedwig fails to connect there is simpy no report about failure it just keeps silent. I guess it'd be nice to know about disconnection and it's causes

**Comment by scrogson** [comment]
@iraasta yeah, I made it so that if it loses connection for whatever reason, that it would just keep trying over and over. I may need to revisit that.

**Comment by scrogson** [comment]
@wende I've addressed this in the new XMPP client lib [Romeo](https://github.com/scrogson/romeo). Hedwig has been completely rewritten and is no longer XMPP specific. I will be adding more docs and updating the changelog, so make sure to check those out for more details. Hope you like :)
