### ISSUE TITLE
Reply to IQ requests

### ISSUE THREAD

**Issue by nrio0** [hedwig-im/hedwig#17]
According to [RFC 3920](http://tools.ietf.org/html/rfc3920#section-9.2.3):

```
An entity that receives an IQ request of type "get" or "set" MUST
reply with an IQ response of type "result" or "error" (the
response MUST preserve the 'id' attribute of the request).
```

I noticed this error when I enabled [XEP-0199](http://xmpp.org/extensions/xep-0199.html) in ejabberd. The server sends a number of ping IQs, but the client doesn't react. After multiple IQ stanzas have been left unanswered, the connection is closed.
I briefly looked at how SleekXMPP handles such IQ stanzas if the plugin for XEP-0199 is not explicitly activated. It responds with an error IQ to all unrecognized IQ stanzas:
https://github.com/fritzy/SleekXMPP/blob/4305eddb4f634803423cd53d193125a63b00769a/sleekxmpp/stanza/iq.py#L84

**Comment by scrogson** [comment]
Hello @nrio0,

This could easily be handled by adding a handler that responds to the incoming `IQ` stanza. Something like this:

```elixir
defmodule MyApp.PingHandler do
  use Hedwig.Handler

  def handle_event(%IQ{from: from, id: id, type: "get"} = iq, opts) do
    stanza = %IQ{to: from, id: id, type: "result"}
    Hedwig.Client.reply(stanza.client, stanza)
    {:ok, opts}
  end

  def handle_event(_, opts), do: {:ok, opts}
end
```

Let me know if you need any further help.
