### ISSUE TITLE
Domain issue in connecting

### ISSUE THREAD

**Issue by TBK145** [hedwig-im/hedwig#18]
I've got a pretty strange problem.
The JID of my account is ``foo@bar.nl``, and the server is ``foo2.bar.nl``. I had this all stored in the config map.
However, the server would always reject the connection after the ``auth`` stanza.
I finally found out that it was because in the first ``stream:stream`` stanza it should say ``bar.nl`` instead of ``foo2.bar.nl`` in the ``to`` attribute.
Currently I've got it hardcoded in the library, but I thought it would be nicer if this could be implemented in some way.

So this is more a proposal; would you be interested in a PR if I fixed this in one of the following ways:
- Add a boolean to the config map, determining if the server property of the config map or the domain part of the JID should be used in the ``to`` attribute of the ``stream:stream`` stanza.
- Parse the ``server`` variable in ``Hedwig.Stanza.start_stream/2`` to only use the ``bar.nl`` part when the ``server`` variable is ``foo.bar.nl``.

I hope this was clear and look forward to a reply.

**Comment by scrogson** [comment]
Ah, I think I see the problem. Let me push a fix and have you test it out.

**Comment by TBK145** [comment]
So what would be the problem? The ``to`` attribute shouldn't use the subdomain?
