### ISSUE TITLE
is there a notion of a brain?

### ISSUE THREAD

**Issue by docteurklein** [hedwig-im/hedwig#25]
If I want to store some information between two messages, what should I do?

Should I use an Agent?

**Comment by scrogson** [comment]
Probably either an Agent or just use ETS for now. I'm still working out how I want to support that. Can you give me a scenario of how you would expect it to work?

**Comment by docteurklein** [comment]
I'm using it like that: https://gist.github.com/docteurklein/791fdc5921d3ef838e64

works OK for my use case.

**Comment by scrogson** [comment]
Yeah, this looks pretty good. I had started working on an `Agent`-based brain earlier, but decided to punt it for later. I know that many people will want to deploy their bot(s) to something like Heroku, which both `Agent` and `ETS` will not be a good solution as the dynos are rebooted at least once a day. So I'd like to make an adapter-based storage solution.

**Comment by docteurklein** [comment]
Sure. An interface/protocol for the brain api would be perfect.

**Comment by scrogson** [comment]
Cool..I'll start on one this week.

**Comment by scrogson** [comment]
Just following up. I haven't had much time lately. If you are interested in helping to flesh out an adapter-based brain, feel free to start a PR.

**Comment by jeffweiss** [comment]
I have a bananas idea of using [riak_dt](http://docs.basho.com/riak/latest/dev/using/data-types/) as an adapter backend, because, well, no reason in particular other than I ought to learn about it... But, it did illuminate some potentially useful Brain operations not previously discussed:

* increment/decrement counter
* add to/remove from set/map

All of which should be relatively straightforward to add to a Brain behaviour I think...

**Comment by knewter** [comment]
@jeffweiss I'm trying to wrap my head around the need for a brain.  I started out thinking I needed one, and instead just wrote an OTP app that my bot was an interface for.  Is there a use case that this doesn't fit?

**Comment by scrogson** [comment]
Hey folks. While the concept of a brain may be necessary for things like hubot, I'm not currently convinced that we need it for hedwig.

I'm definitely still open to the idea, but until we run into an issue where we absolutely need one, I'm going to call this one closed.
