### ISSUE TITLE
how to deploy to heroku?

### ISSUE THREAD

**Issue by docteurklein** [hedwig-im/hedwig#32]
I'm blindly trying to have a working Procfile.
However the "web" process type does not seem to work.
I tried:

```
bot: mix run --no-halt
```

and
```
web: mix run --no-halt
```

same effect. no logs, nothing.

Do you have any experience regarding heroku deployment?
PS: i'm using:

```
 % heroku config
=== edgar-hedwig Config Vars
BUILDPACK_URL: https://github.com/HashNuke/heroku-buildpack-elixir.git
MIX_ENV:       prod
```

**Comment by meatherly** [comment]
Heroku kills web apps if they don't respond to $PORT in 60 seconds. see: https://devcenter.heroku.com/articles/error-codes#r10-boot-timeout

I would just write a simple cowboy process that listens to and set to port to `System.get_env('PORT') || 4000`

**Comment by docteurklein** [comment]
@meatherly thanks for the tips!
I know about the "web" process specificities, but it amazes me that heroku forces you to create a useless web process just to let other dynos live.

From what I read here https://devcenter.heroku.com/articles/run-non-web-java-processes-on-heroku it seems we could run whatever long-running process without any web process.

Thoughts?

**Comment by bbrock25** [comment]
@docteurklein is there a reason why you cannot use a worker process? I have an elixir chat bot running as a worker on heroku that has stayed alive for months now without a web process.

**Comment by docteurklein** [comment]
@bbrock25 thanks for the feedback
I tried at first to define a worker process only, but didn't get it to work.
What does your Procfile look like, and how are you starting it?
I tried with

    bot: mix run --no-halt

and then push to deploy.

**Comment by docteurklein** [comment]
EDIT: i just tried to run it with `heroku scale bot=1` and it seems to work. Still not sure why it doesn't at git push.

**Comment by bbrock25** [comment]
You probably needed to turn the worker on before it would automatically deploy. I'd imagine that deploying with git push should be fine now.

**Comment by docteurklein** [comment]
@bbrock25 thanks! 
I didn't notice you added your Procfile, sorry to ask again how it looked like.
Anyway, I guess I can close this issue now?
