### ISSUE TITLE
Changes to Hedwig.Message

### ISSUE THREAD

**Issue by scrogson** [hedwig-im/hedwig#38]
Hey Hedwig adapter folks!

@jwarlander @bryanjos @jeffweiss

I've just pushed some changes to Hedwig based on some irritations I found with my implementation and I wanted to get things squared up before pulling the trigger on `1.0`.

Here are the changes: https://github.com/hedwig-im/hedwig/commit/18273f14fb8a6d5869551f0c7a3d2eebb2b3662a

All you'll need to do for your adapters is remove the `adapter` key from the `%Hedwig.Message{}` struct. The rest should be transparent.

If you have any other feedback...I would love to hear it!

**Comment by jeffweiss** [comment]
@scrogson :+1: corresponding change in hedwig_irc is jeffweiss/hedwig_irc@43e414435bdbead002113a7e889a9d8168806f2e

**Comment by bryanjos** [comment]
@scrogson :+1: works perfectly!
