### ISSUE TITLE
I created a Flowdock adapter

### ISSUE THREAD

**Issue by supernullset** [hedwig-im/hedwig#43]
Hey everyone, I built a [Flowdock](https://www.flowdock.com) adapter which you can see [here](https://github.com/supernullset/hedwig_flowdock) which is still very much WIP, but is working. Im interested in getting it moved over to the hedwig-im organization so that it can be found more easily! What can I do to help out?

Also, thanks to @jeffweiss for encouraging me to make an adapter after his presentation at the Erlang user group in Seattle.

**Comment by scrogson** [comment]
@supernullset, exciting to hear folks are starting to build other adapters!

I'm currently not interested in moving adapters into the hedwig-im org. This would end up becoming more of a burden for me (managing issues and PRs  for code I have not written). I would much rather have a list of adapters added to the README.

Also, all adapters should follow the `hedwig_<adapter>` naming convention, and that would make it easier to find on hex.pm.

Thank you!

**Comment by supernullset** [comment]
@scrogson Thanks for the quick reply! Ill make sure that i'm following the naming convention. Shall I open up a PR for updating the README once I upload the package to hex.pm?

**Comment by scrogson** [comment]
Yes! Please do!
