### ISSUE TITLE
Crash when trying to create a secure connection

### ISSUE THREAD

**Issue by foldericon** [hedwig-im/hedwig#66]
So my SMTP server is listening on localhost and I chose `.plain` for the secure option.
Nonetheless, Hedwig tries to establish a TLS secured connection when the server supports it.
And that's where my crash occurs. One of the parameters you pass to `TLS.Socket`in your `starttls` method is nil and gets force unwrapped later. I hope that helps fixing the issue, but you should also consider changing the approach here. Why do you want to force a TLS connection just because the server supports it? Some people just want to connect to an SMTP server that is listening on the loopback adapter and I don't get the point of creating an encrypted connection to localhost.

**Comment by scrogson** [comment]
@foldericon I'm not following how this has anything to do with Hedwig itself. Can you explain in more detail?

* Which version of Hedwig are you using?
* Which adapter are you using?

**Comment by foldericon** [comment]
Oh shit, I'm sorry, this is the wrong project, I meant https://github.com/onevcat/Hedwig
I should just go to sleep next time.

**Comment by scrogson** [comment]
No worries, thanks.
