### ISSUE TITLE
Ability to listen but not respond

### ISSUE THREAD

**Issue by praveenperera** [hedwig-im/hedwig#83]
I would like to create an IRC logger I would like to do something like this

```
  hear ~r/.*/i, msg do
    save_to_db(msg)
  end
```

But if I do this write now each message causes the gen server to die because the hear macro does not end with an emote, reply and send

**Comment by scrogson** [comment]
@praveenperera the responder just needs to return `:ok`.

**Comment by praveenperera** [comment]
Perfect that works @scrogson thanks!
